url: "http://paris.afup.org"

title: "AFUP Paris"
description: >-
  Antenne AFUP sur Paris
twitter_username: AFUP_Paris
meetup_url: "https://www.meetup.com/fr-FR/afup-paris-php"

permalink: /posts/:title

ga_ua: ""
home_featured_articles_count: 1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
   - Makefile
   - docker-compose.yml
   - docker-compose.override.yml-dist
   - docker-compose.override.yml
   - Gemfile
   - Gemfile.lock

feed:
  path: feed

